name: wolnakeja
description: Rezerwuj miejsce postojowe dla Twojego jachtu. Wygodnie, szybko i pewnie.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  responsive_builder: ^0.4.1
  seo_renderer: ^0.4.0
  transparent_image: ^2.0.0
  url_launcher: ^6.0.20
  

dev_dependencies:
  custom_lint: ^0.6.4
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  leancode_lint: ^13.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/footer/
    - assets/images/mainSlider/
    - assets/images/party&events/
    - assets/images/portPanel/
    - assets/images/uspRow/
    - assets/images/valuesProduct/
    - assets/images/
    - assets/images/aboutwk/
    - assets/images/NavigationBarMobile/
    - assets/documents/


  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf

