name: Dart. Install dependencies. Check formatting. Analyze project.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.3

      - run: flutter --version

      - name: Install dependencies 
        run: flutter pub get

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed . 

      - name: Analyze project source
        run: dart analyze --fatal-infos